1) Write a function in python that inputs a dataframe and identify which columns have date in them. Using these date columns make new columns which are difference between these columns taking 2 at a time. (for instance if there is date1, date2, date3 columns, output should be like date1-date2, date2-date3, date1-date3). For this problem only, print out data in the colab.

Thing to consider

· Date column might have some invalid entries in them

· Date can be of different format throughout the column

· Code should be efficient and fast

· Code should be well commented and easy to interpret

· Use google Colab

· Code should be robust enough to run on any dataset

· Make a dummy dataset by yourself.

In [1]:
import pandas as pd

## Created a Dummy Data Set in Excel and uploading it in colab

In [2]:
from google.colab import files

In [6]:
uploaded = files.upload()

Saving Lannet.xlsx to Lannet (1).xlsx

In [7]:
df = pd.read_excel(uploaded['Lannet.xlsx'])

In [8]:
df

       date1      date2      date3
0 2012-03-13 2011-03-31 1990-04-09
1 2019-06-03 2015-01-26 1989-12-15
2 2004-12-21        NaT 2001-11-20
3        NaT 2024-03-21 2017-08-20
4 2021-12-13 2016-02-15        NaT
5 2016-12-31 2014-05-13 2003-07-31
6 2000-07-31 1997-06-26 1997-02-23
7 2019-04-14 2013-02-05 2003-06-12
8 2021-03-10 2002-05-17 1998-05-14

## Creating a column which is differenece betwen the 2 columns

In [9]:
def dif():
      df.insert(3,'date1-date2',(df.date1-df.date2))
      df.insert(4,'date2-date3',(df.date2-df.date3))
      df.insert(5,'date1-date3',(df.date1-df.date3))

In [10]:
dif()

In [11]:
df

       date1      date2      date3 date1-date2 date2-date3 date1-date3
0 2012-03-13 2011-03-31 1990-04-09    348 days   7661 days   8009 days
1 2019-06-03 2015-01-26 1989-12-15   1589 days   9173 days  10762 days
2 2004-12-21        NaT 2001-11-20         NaT         NaT   1127 days
3        NaT 2024-03-21 2017-08-20         NaT   2405 days         NaT
4 2021-12-13 2016-02-15        NaT   2128 days         NaT         NaT
5 2016-12-31 2014-05-13 2003-07-31    963 days   3939 days   4902 days
6 2000-07-31 1997-06-26 1997-02-23   1131 days    123 days   1254 days
7 2019-04-14 2013-02-05 2003-06-12   2259 days   3526 days   5785 days
8 2021-03-10 2002-05-17 1998-05-14   6872 days   1464 days   8336 days

2) Write a function in python that take dataframe as input and drop columns having Pearson correlation more than 0.85

Thing to consider

· Code should drop least amount of variable as possible. (this is an important point)

· Code should be efficient and fast

· Code should be well commented and easy to interpret

· Use google Colab

· Code should be robust enough to run on any dataset

· Make a dummy dataset by yourself or pass any publicly available dataset to test out your logic

## Uploading a Dummy Data Set

In [48]:
uploaded = files.upload()

Saving Major_Project_Data.xlsx to Major_Project_Data (1).xlsx

In [49]:
df2 = pd.read_excel(uploaded['Major_Project_Data.xlsx'])

In [54]:
df2

       Unnamed: 0  Clothing ID  Age  ...   Division Name Department Name  Class Name
0               0          767   33  ...       Initmates        Intimate   Intimates
1               1         1080   34  ...         General         Dresses     Dresses
2               2         1077   60  ...         General         Dresses     Dresses
3               3         1049   50  ...  General Petite         Bottoms       Pants
4               4          847   47  ...         General            Tops     Blouses
...           ...          ...  ...  ...             ...             ...         ...
23481       23481         1104   34  ...  General Petite         Dresses     Dresses
23482       23482          862   48  ...  General Petite            Tops       Knits
23483       23483         1104   31  ...  General Petite         Dresses     Dresses
23484       23484         1084   28  ...         General         Dresses     Dresses
23485       23485         1104   52  ...  General Petite         Dresses     Dresses

[23486 rows x 11 columns]

## Checking Pearson Correlation

In [50]:
pearsoncorr=  df2.corr(method='pearson')

In [51]:
pearsoncorr

                         Unnamed: 0  ...  Positive Feedback Count
Unnamed: 0                 1.000000  ...                -0.002907
Clothing ID               -0.006072  ...                 0.046356
Age                       -0.007749  ...                 0.043079
Rating                    -0.002568  ...                -0.064961
Recommended IND           -0.003887  ...                -0.069045
Positive Feedback Count   -0.002907  ...                 1.000000

[6 rows x 6 columns]

## Dropping the Columns having pearson correaltion more than 0.85

In [55]:
df2.drop(pearsoncorr>0.85,axis=1,inplace=True)
df2

                                                   Title  ... Class Name
0                                                    NaN  ...  Intimates
1                                                    NaN  ...    Dresses
2                                Some major design flaws  ...    Dresses
3                                       My favorite buy!  ...      Pants
4                                       Flattering shirt  ...    Blouses
...                                                  ...  ...        ...
23481                     Great dress for many occasions  ...    Dresses
23482                         Wish it was made of cotton  ...      Knits
23483                              Cute, but see through  ...    Dresses
23484  Very cute dress, perfect for summer parties an...  ...    Dresses
23485                    Please make more like this one!  ...    Dresses

[23486 rows x 5 columns]